[package]
name = "dkim"
version = "0.1.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"

[dependencies]
email = "0.0"
sha-1 = "0.9"
sha2 = "0.9"
ring = ""
base64 = ""
prettydiff = ""
rsa = ""
string-tools = ""